// The Learn curriculum: units -> lessons -> steps. Data only; learn.js plays it and learn-rules.js checks it.
// Every goal has a reference `solution`, every star course a `par`, and test/lessons.test.js proves both
// on the board, so no exercise can be unsolvable or accept a wrong idea.
//
// Step types
//   show     text + position, with optional arrows [[from, to]] and marked squares
//   squares  click the named squares in turn: targets [[square | 'a|b', prompt], ...]
//   stars    move freely (the other side never moves) to collect every star in `par` moves;
//            captureAll: also take every enemy piece; guarded: never stop on an attacked square
//   goal     one move that passes `goal` (see TESTS in learn-rules.js)
//   line     play the given moves; the replies are automatic; a different mate on the last move counts
//   play     mate the lone king against the practice opponent within `limit` moves
//   quiz     pick the right answer; `verify` lets the tests check it on the board
import { fen } from './learn-rules.js';

const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const EMPTY = fen();
const E4E5 = 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2';
const E4E5NF3NC6 = 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3';
const ITALIAN = 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4';
const SCHOLAR = 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4';
const all = (from, list) => list.split(' ').map((to) => [from, to]);
const ray = (a, b) => {
  const files = 'abcdefgh';
  const [f1, r1, f2, r2] = [files.indexOf(a[0]), +a[1], files.indexOf(b[0]), +b[1]];
  const n = Math.max(Math.abs(f2 - f1), Math.abs(r2 - r1));
  return Array.from({ length: n + 1 }, (_, i) =>
    files[f1 + (Math.sign(f2 - f1) * i)] + (r1 + Math.sign(r2 - r1) * i));
};

export const UNITS = [
  {
    id: 'board',
    title: 'The board',
    text: 'Squares, files, ranks and where every piece starts.',
    lessons: [
      {
        id: 'squares',
        title: 'Files, ranks and squares',
        summary: 'Name every square on the board.',
        icon: 'board',
        steps: [
          { type: 'show', fen: EMPTY, marks: ray('e1', 'e8'),
            text: 'The board has 64 squares in 8 columns and 8 rows. The columns are called files and are named with the letters a to h. This one is the e-file.' },
          { type: 'show', fen: EMPTY, marks: ray('a4', 'h4'),
            text: 'The rows are called ranks and are numbered 1 to 8, counting from White\'s side. This is the 4th rank.' },
          { type: 'show', fen: EMPTY, marks: ['e4'],
            text: 'A square is named by its file and then its rank. The e-file and the 4th rank cross on e4.' },
          { type: 'squares', fen: EMPTY, text: 'Find the squares. The letters and numbers along the edge of the board help.',
            targets: [['e4', 'Click e4.'], ['a1', 'Click a1.'], ['h8', 'Click h8.'], ['d5', 'Click d5.'], ['c3', 'Click c3.'], ['f7', 'Click f7.'], ['b6', 'Click b6.'], ['g2', 'Click g2.']] },
          { type: 'quiz', text: 'When you set up a board, what colour must the corner square on your right-hand side be?',
            choices: ['Light', 'Dark'], answer: 0,
            after: 'Light on the right. For White that is h1, for Black a8. If a1 is not dark, the board is turned the wrong way.' },
        ],
      },
      {
        id: 'setup',
        title: 'The starting position',
        summary: 'Where the 32 pieces stand at the start.',
        icon: 'layers',
        steps: [
          { type: 'show', fen: START,
            text: 'Each side starts with 16 pieces: a king, a queen, two rooks, two bishops, two knights and eight pawns. The pawns stand in front, on the 2nd rank for White and the 7th rank for Black.' },
          { type: 'show', fen: START, marks: ['d1', 'd8', 'e1', 'e8'],
            text: 'The queen starts on a square of her own colour: the white queen on the light square d1, the black queen on the dark square d8. The kings stand beside them on e1 and e8.' },
          { type: 'squares', fen: START, text: 'Find the pieces.',
            targets: [['e1', 'Click the white king.'], ['d8', 'Click the black queen.'], ['b1|g1', 'Click a white knight.'], ['a8|h8', 'Click a black rook.'], ['c1|f1', 'Click a white bishop.']] },
          { type: 'quiz', fen: START, text: 'Who makes the first move of the game?',
            choices: ['White', 'Black', 'Whoever wins a coin toss'], answer: 0,
            after: 'White always moves first. Then the players take turns, one move each.' },
        ],
      },
    ],
  },
  {
    id: 'pieces',
    title: 'How the pieces move',
    text: 'Move each piece, collect the stars and capture what you can.',
    lessons: [
      {
        id: 'rook',
        title: 'The rook',
        summary: 'Straight lines along files and ranks.',
        icon: 'r',
        steps: [
          { type: 'show', fen: fen('Rd4'), arrows: all('d4', 'd8 d1 a4 h4'),
            text: 'The rook moves in a straight line along a file or a rank, as many squares as it likes. It can\'t jump over other pieces.' },
          { type: 'stars', fen: fen('Ra1'), stars: ['a5', 'e5', 'e8'], par: 3,
            text: 'Collect every star with the rook. Try to use as few moves as possible.' },
          { type: 'stars', fen: fen('Rd4'), stars: ['h4', 'h8', 'b8', 'b2'], par: 4,
            text: 'Collect the stars again. Every move can cross the whole board.' },
          { type: 'stars', fen: fen('Ra1', 'Na6 Bf6 Nf2 Bc2'), captureAll: true, par: 4,
            text: 'Capture all the black pieces. They stand still; only you move. A piece captures by moving onto the square of an enemy piece.' },
        ],
      },
      {
        id: 'bishop',
        title: 'The bishop',
        summary: 'Diagonals, always on one colour.',
        icon: 'b',
        steps: [
          { type: 'show', fen: fen('Bd4'), arrows: all('d4', 'a1 h8 a7 g1'),
            text: 'The bishop moves diagonally, as many squares as it likes. It never changes colour: a bishop on a dark square stays on dark squares for the whole game.' },
          { type: 'stars', fen: fen('Bc1'), stars: ['h6', 'f8', 'a3'], par: 3,
            text: 'Collect every star with the bishop.' },
          { type: 'stars', fen: fen('Bf1'), stars: ['b5', 'e8', 'h5', 'd1'], par: 4,
            text: 'Now with the light-squared bishop.' },
          { type: 'quiz', fen: fen('Bc1'), marks: ['e4'], text: 'This bishop starts on the dark square c1. Can it ever reach e4?',
            choices: ['Yes', 'No'], answer: 1,
            after: 'e4 is a light square, and a bishop never leaves its colour. That is why each side has one light-squared and one dark-squared bishop.' },
        ],
      },
      {
        id: 'queen',
        title: 'The queen',
        summary: 'Rook and bishop in one piece.',
        icon: 'q',
        steps: [
          { type: 'show', fen: fen('Qd4'), arrows: all('d4', 'd8 d1 a4 h4 a1 h8 a7 g1'),
            text: 'The queen moves like a rook and a bishop together: along files, ranks and diagonals, as far as she likes. She is the strongest piece.' },
          { type: 'stars', fen: fen('Qd1'), stars: ['d7', 'a4', 'h4'], par: 3,
            text: 'Collect every star with the queen.' },
          { type: 'stars', fen: fen('Qd1', 'Ra4 Bg4 Nd6'), captureAll: true, guarded: true, par: 4,
            text: 'Capture all three pieces, but never stop on a square a black piece attacks, or your queen would be taken. The rook protects the bishop, so the order matters.' },
        ],
      },
      {
        id: 'king',
        title: 'The king',
        summary: 'One square at a time, never into danger.',
        icon: 'k',
        steps: [
          { type: 'show', fen: fen('Ke4'), arrows: all('e4', 'd3 e3 f3 d4 f4 d5 e5 f5'),
            text: 'The king moves one square in any direction. He is slow, but he is the one piece you can never lose.' },
          { type: 'stars', fen: fen('Ke1'), stars: ['e3', 'g4', 'g6'], par: 6,
            text: 'Collect the stars with the king. Moving diagonally saves steps.' },
          { type: 'stars', fen: fen('Ke1', 'Nd5'), stars: ['e5'], par: 4,
            text: 'The king may never step onto a square an enemy piece attacks. The knight on d5 guards c3, e3 and f4, among others, so the board will not let your king go there. Reach the star.' },
        ],
      },
      {
        id: 'knight',
        title: 'The knight',
        summary: 'The L-shaped jump.',
        icon: 'n',
        steps: [
          { type: 'show', fen: fen('Nd4'), arrows: all('d4', 'b3 b5 c2 c6 e2 e6 f3 f5'),
            text: 'The knight moves in an L: two squares in one direction, then one square to the side. It is the only piece that jumps over others.' },
          { type: 'stars', fen: fen('Ng1'), stars: ['f3', 'e5', 'd7', 'b8'], par: 4,
            text: 'Collect every star with the knight.' },
          { type: 'stars', fen: fen('Na1'), stars: ['h8'], par: 6,
            text: 'Take the knight from one corner to the other. The shortest way takes six jumps.' },
          { type: 'show', fen: START, arrows: [['b1', 'a3'], ['b1', 'c3'], ['g1', 'f3'], ['g1', 'h3']],
            text: 'Because it jumps, a knight can leave its starting square while the pawns are still in front of it.' },
          { type: 'quiz', fen: fen('Ne4'), text: 'The knight on e4 stands on a light square. Where does it land after one move?',
            choices: ['On a light square', 'On a dark square', 'It depends on the move'], answer: 1,
            after: 'A knight always changes colour when it moves: light to dark, dark to light.' },
        ],
      },
      {
        id: 'pawn',
        title: 'The pawn',
        summary: 'Forward to move, diagonally to capture.',
        icon: 'p',
        steps: [
          { type: 'show', fen: fen('e2 d4'), arrows: [['e2', 'e3'], ['e2', 'e4'], ['d4', 'd5']],
            text: 'A pawn moves straight forward, one square at a time. From its starting square it may move two squares at once. A pawn never moves backwards.' },
          { type: 'show', fen: fen('e4', 'd5 e5 f5'), arrows: [['e4', 'd5'], ['e4', 'f5']],
            text: 'A pawn captures differently: one square diagonally forward. It can\'t capture straight ahead, so the pawn on e5 simply blocks it.' },
          { type: 'stars', fen: fen('e2'), stars: ['e4', 'e6'], par: 3,
            text: 'Collect the stars with the pawn. Use the double step.' },
          { type: 'stars', fen: fen('b2', 'Nc3 Bb4 Rc5 Qd6'), captureAll: true, par: 4,
            text: 'Capture all the black pieces with the pawn. Remember: pawns capture diagonally.' },
          { type: 'quiz', fen: fen('e4', 'e5'), text: 'The white pawn on e4 faces the black pawn on e5. Can it move?',
            choices: ['Yes, it can capture the pawn', 'No, it is blocked'], answer: 1,
            after: 'Pawns never capture straight ahead. With a piece right in front of it, a pawn is stuck until something changes.' },
        ],
      },
    ],
  },
  {
    id: 'value',
    title: 'Capturing and value',
    text: 'What the pieces are worth, how to win them and how to keep yours.',
    lessons: [
      {
        id: 'values',
        title: 'What pieces are worth',
        summary: 'Pawn 1, knight 3, bishop 3, rook 5, queen 9.',
        icon: 'gem',
        steps: [
          { type: 'show', fen: fen('Qd4 Re4 Bc4 Nf4 b4'),
            text: 'Pieces are worth different amounts. The usual scale: pawn 1, knight 3, bishop 3, rook 5, queen 9. The king has no points: it can never be traded, and losing it loses the game.' },
          { type: 'quiz', text: 'Which is worth more?', choices: ['A rook', 'A bishop and a pawn', 'They are equal'], answer: 0,
            after: 'A rook is 5, a bishop and a pawn are 3 + 1 = 4.' },
          { type: 'quiz', text: 'Your queen can take a knight, but then a pawn takes your queen. Is that a good trade?',
            choices: ['Yes, I took a piece', 'No, I gave 9 points for 3'], answer: 1,
            after: 'Before you capture, check what can take back. Losing the queen for a knight costs 6 points.' },
          { type: 'quiz', text: 'You give up a rook and win a bishop and a knight. Who comes out ahead?',
            choices: ['You: 6 points for 5', 'Your opponent', 'Nobody'], answer: 0,
            after: 'Two minor pieces (6) are usually worth a little more than a rook (5).' },
        ],
      },
      {
        id: 'free',
        title: 'Take what is free',
        summary: 'Win pieces nothing defends.',
        icon: 'target',
        steps: [
          { type: 'show', fen: fen('Kg1 Qd2 Nf3 f2 g2 h2', 'Kg8 Bb4 Ne5 d6 e7 f7 g7 h7'), marks: ['b4'],
            text: 'A piece is hanging when nothing defends it. Take a hanging piece and you win it for free. Pieces that are defended can be taken back.' },
          { type: 'goal', fen: fen('Kg1 Qd2 Nf3 f2 g2 h2', 'Kg8 Bb4 Ne5 d6 e7 f7 g7 h7'), goal: 'free', solution: 'Qxb4',
            text: 'One black piece is hanging. Take it for free.',
            after: 'The bishop on b4 had no defender. The knight on e5 and the pawn on d6 are protected by pawns.' },
          { type: 'goal', fen: fen('Kg1 Re1 Nc3 f2 g2 h2', 'Kg8 Be4 Nd5 e6 f7 g7 h7'), goal: 'free', solution: 'Rxe4',
            text: 'Find the free piece again.',
            after: 'Nothing defends the bishop on e4. The knight on d5 is protected by the pawn on e6.' },
          { type: 'goal', fen: fen('Kg1 Qd1 f2 g2 h2', 'Kg8 Nd4 Bg4 c5 f7 g7 h7'), goal: 'free', solution: 'Qxg4',
            text: 'Your queen is attacked. Answer by winning a piece.',
            after: 'The bishop on g4 attacked your queen but had no defender. Taking the knight on d4 would lose the queen to the pawn on c5.' },
        ],
      },
      {
        id: 'protect',
        title: 'Keep your pieces',
        summary: 'Defend a piece or move it to safety.',
        icon: 'shield',
        steps: [
          { type: 'show', fen: fen('Kg1 Ne5 d2 f2 g2 h2', 'Kg8 Re8 f7 g7 h7'), arrows: [['e8', 'e5']],
            text: 'When a piece of yours is attacked, you can defend it, so that if it is taken you take back, or you can move it to a square where it is safe.' },
          { type: 'goal', fen: fen('Kg1 Ne5 d2 f2 g2 h2', 'Kg8 Re8 f7 g7 h7'), goal: ['protect', 'e5'], solution: 'd4',
            text: 'The rook attacks your knight. Defend the knight with a pawn.',
            after: 'Now if the rook takes the knight, the pawn takes the rook: Black would give a rook (5) for a knight (3).' },
          { type: 'goal', fen: fen('Kg1 Qd4 f2 g2 h2', 'Kg8 Nf6 Bb6 e5 f7 g7 h7'), goal: ['safe', 'd4'], solution: 'Qd1',
            text: 'Your queen is attacked by a pawn and a bishop. Move her to a square where nothing can take her.',
            after: 'Before you move an attacked piece, check the new square: the knight, the bishop and the pawns all guard squares.' },
        ],
      },
    ],
  },
  {
    id: 'check',
    title: 'Check',
    text: 'Attacking the king, and getting out of check.',
    lessons: [
      {
        id: 'give-check',
        title: 'Giving check',
        summary: 'Attack the king.',
        icon: 'crosshair',
        steps: [
          { type: 'show', fen: fen('Kg1 Re1', 'Ke8', { turn: 'b' }), arrows: [['e1', 'e8']],
            text: 'A king that is attacked is in check. The player in check must get out of it on the very next move. You may never make a move that leaves your own king in check.' },
          { type: 'goal', fen: fen('Kg1 Ra1', 'Ke8 f7 g7 h7'), goal: 'check', solution: 'Ra8+',
            text: 'Give check with the rook.' },
          { type: 'goal', fen: fen('Kg1 Bf1', 'Ke8'), goal: 'check', solution: 'Bb5+',
            text: 'Give check with the bishop.' },
          { type: 'goal', fen: fen('Kg1 Ne4', 'Ke8'), goal: 'check', solution: 'Nf6+',
            text: 'Give check with the knight.' },
        ],
      },
      {
        id: 'escape',
        title: 'Getting out of check',
        summary: 'Move, block or capture.',
        icon: 'shield',
        steps: [
          { type: 'show', fen: fen('Ke1 Bc1 a2 b2', 'Kg8 Re8'), arrows: [['e8', 'e1']],
            text: 'There are three ways out of check: move the king to a safe square, block the check by putting a piece in between, or capture the piece that gives check.' },
          { type: 'goal', fen: fen('Ke1 Bc1 a2 b2', 'Kg8 Re8'), goal: ['escape', 'king'], solution: 'Kd2',
            text: 'You are in check. Get out of it by moving the king.' },
          { type: 'goal', fen: fen('Kg1 Nc3 f2 g2', 'Kg8 Ra1 f7 g7 h7'), goal: ['escape', 'block'], solution: 'Nd1',
            text: 'Now block the check.',
            after: 'The knight stands between the rook and the king. Moving the king to h2 was possible too, but here you practised the block.' },
          { type: 'goal', fen: fen('Kg1 f2 g2 h2', 'Kg8 Nf3 f7 g7 h7'), goal: ['escape', 'capture'], solution: 'gxf3',
            text: 'Get out of check by capturing the piece that gives it.',
            after: 'A knight check can\'t be blocked, because the knight jumps. Capturing it is best: you also win a piece.' },
          { type: 'quiz', text: 'Can you ever make a move that leaves your own king in check?',
            choices: ['Yes, if it wins material', 'No, never'], answer: 1,
            after: 'Such a move is illegal. The board in this app simply will not allow it.' },
        ],
      },
    ],
  },
  {
    id: 'mate',
    title: 'Checkmate',
    text: 'The goal of the game, and the draw to avoid.',
    lessons: [
      {
        id: 'mate-stalemate',
        title: 'Checkmate and stalemate',
        summary: 'Game over, or a draw.',
        icon: 'crown',
        steps: [
          { type: 'show', fen: fen('Kg1 Rd8', 'Kg8 f7 g7 h7', { turn: 'b' }), arrows: [['d8', 'g8']],
            text: 'Checkmate: the king is in check and there is no way out, no safe square, no block and no capture. Checkmate wins the game.' },
          { type: 'show', fen: fen('Kf7 Qg6', 'Kh8', { turn: 'b' }),
            text: 'Stalemate: the player to move is not in check but has no legal move. That is a draw, however many pieces the other side has.' },
          { type: 'quiz', fen: fen('Kf6 Qg7', 'Kh8', { turn: 'b' }), verify: 'mate', text: 'Black to move. Checkmate or stalemate?',
            choices: ['Checkmate', 'Stalemate'], answer: 0,
            after: 'The queen gives check, the king protects her, and every square around the black king is covered.' },
          { type: 'quiz', fen: fen('Ke1 Qb6', 'Ka8', { turn: 'b' }), verify: 'stalemate', text: 'Black to move. Checkmate or stalemate?',
            choices: ['Checkmate', 'Stalemate'], answer: 1,
            after: 'The black king is not in check, but a7, b7 and b8 are all covered. Black has no move: a draw.' },
        ],
      },
      {
        id: 'mate-rooks',
        title: 'Mate with the rooks',
        summary: 'The back rank and the ladder.',
        icon: 'r',
        steps: [
          { type: 'goal', fen: fen('Kg1 Rd1 f2 g2 h2', 'Kg8 f7 g7 h7'), goal: 'mate', solution: 'Rd8#',
            text: 'Checkmate in one move. The black king is boxed in by its own pawns.',
            after: 'This is the back-rank mate, one of the most common mates in real games.' },
          { type: 'goal', fen: fen('Kc1 Ra1 Rb7', 'Kg8'), goal: 'mate', solution: 'Ra8#',
            text: 'Checkmate in one. One rook already guards the 7th rank.' },
          { type: 'goal', fen: fen('Kg6 Ra1', 'Kh8'), goal: 'mate', solution: 'Ra8#',
            text: 'Checkmate in one with the help of your king.' },
        ],
      },
      {
        id: 'mate-queen',
        title: 'Mate with the queen',
        summary: 'The queen and a helper.',
        icon: 'q',
        steps: [
          { type: 'goal', fen: fen('Kf6 Qa7', 'Kh8'), goal: 'mate', solution: 'Qg7#',
            text: 'Checkmate in one. Your king can protect the queen.' },
          { type: 'goal', fen: fen('Kb6 Qc1', 'Ka8'), goal: 'mate', solution: 'Qc8#',
            text: 'Checkmate in one.' },
          { type: 'goal', fen: fen('Kg1 Qd4 Bb2', 'Kg8 f7 h7'), goal: 'mate', solution: 'Qg7#',
            text: 'Checkmate in one. Your bishop on b2 helps from far away.' },
          { type: 'goal', fen: SCHOLAR, goal: 'mate', solution: 'Qxf7#',
            text: 'Checkmate in one, straight from the opening.',
            after: 'This is Scholar\'s Mate: the queen, backed by the bishop, takes on f7, the square only the king defends.' },
        ],
      },
      {
        id: 'mate-knight',
        title: 'Smothered mate',
        summary: 'When the king\'s own pieces trap it.',
        icon: 'n',
        steps: [
          { type: 'goal', fen: fen('Kg1 Ng5', 'Kh8 Rg8 g7 h7'), goal: 'mate', solution: 'Nf7#',
            text: 'Checkmate in one with the knight.',
            after: 'Smothered mate: the king is surrounded by its own pieces, and a knight check can\'t be blocked.' },
          { type: 'line', fen: fen('Kg1 Qc4 Nf7 g2 h2', 'Kg8 Rf8 g7 h7'), moves: ['Nh6+', 'Kh8', 'Qg8+', 'Rxg8', 'Nf7#'],
            text: 'The famous smothered mate in three. Start with a knight check that also uncovers the queen.',
            after: 'Knight check, queen sacrifice on g8, and the knight mates on f7: the rook blocks the king\'s last square.' },
        ],
      },
      {
        id: 'stalemate',
        title: 'Avoid stalemate',
        summary: 'Win, don\'t draw.',
        icon: 'hourglass',
        steps: [
          { type: 'goal', fen: fen('Kf7 Qe6', 'Kh8'), goal: 'mate', solution: 'Qh6#',
            text: 'White to move. Several moves here stalemate the black king and throw the win away. Find a checkmate.',
            after: 'Qg6 would leave the black king without a move while not in check: stalemate. Always leave the king a move until you can mate.' },
          { type: 'quiz', text: 'Black has only a king. It is not in check but has no legal move, and it is Black\'s turn. What is the result?',
            choices: ['White wins', 'A draw by stalemate'], answer: 1,
            after: 'Stalemate is a draw, no matter how much material White has.' },
        ],
      },
    ],
  },
  {
    id: 'rules',
    title: 'Special rules',
    text: 'Castling, en passant, promotion and draws.',
    lessons: [
      {
        id: 'castling',
        title: 'Castling',
        summary: 'King to safety, rook into play.',
        icon: 'shield',
        steps: [
          { type: 'show', fen: fen('Ke1 Ra1 Rh1 a2 b2 c2 f2 g2 h2', 'Ke8', { castling: 'KQ' }), arrows: [['e1', 'g1'], ['h1', 'f1']],
            text: 'Castling: the king moves two squares towards a rook, and that rook jumps to the square on the king\'s other side. It is the only move with two pieces at once.' },
          { type: 'goal', fen: fen('Ke1 Rh1 d2 e2 f2 g2 h2', 'Ke8', { castling: 'K' }), goal: ['castle', 'king'], solution: 'O-O',
            text: 'Castle on the kingside: drag the king two squares to the right.' },
          { type: 'goal', fen: fen('Ke1 Ra1 a2 b2 c2 d2', 'Ke8', { castling: 'Q' }), goal: ['castle', 'queen'], solution: 'O-O-O',
            text: 'Castle on the queenside: the king goes two squares to the left, to c1, and the rook to d1.' },
          { type: 'quiz', text: 'Which of these does NOT stop you from castling?',
            choices: ['Your king is in check', 'The king or that rook has moved before', 'The king would pass over an attacked square', 'The rook passes over an attacked square'], answer: 3,
            after: 'Only the king\'s path matters: no castling out of check, through check or into check. The rook may cross an attacked square.' },
          { type: 'goal', fen: fen('Ke1 Ra1 Rh1 a2 b2 c2 f2 g2 h2', 'Ke8 Bc4', { castling: 'KQ' }), goal: ['castle', 'queen'], solution: 'O-O-O',
            text: 'Castle to the side where it is allowed.',
            after: 'The bishop on c4 attacks f1, so the king can\'t cross it to castle on the kingside.' },
        ],
      },
      {
        id: 'en-passant',
        title: 'En passant',
        summary: 'The pawn capture in passing.',
        icon: 'p',
        steps: [
          { type: 'show', fen: fen('Ke1 e5', 'Ke8 d5', { ep: 'd6' }), arrows: [['d7', 'd5'], ['e5', 'd6']],
            text: 'En passant: when a pawn moves two squares and lands right beside an enemy pawn, that pawn may capture it as if it had moved only one square. It is allowed only on the very next move.' },
          { type: 'goal', fen: fen('Ke1 e5', 'Ke8 d5', { ep: 'd6' }), goal: 'enpassant', solution: 'exd6',
            text: 'Black has just played d7-d5. Take the pawn en passant.',
            after: 'Your pawn went to d6, the square the black pawn skipped, and the pawn on d5 disappeared.' },
          { type: 'goal', fen: fen('Ke1 e4', 'Ke8 d4', { turn: 'b', ep: 'e3' }), goal: 'enpassant', solution: 'dxe3',
            text: 'Now you play Black. White has just played e2-e4. Take it en passant.' },
        ],
      },
      {
        id: 'promotion',
        title: 'Promotion',
        summary: 'A pawn becomes a queen.',
        icon: 'crown',
        steps: [
          { type: 'show', fen: fen('Ke1 b7', 'Kh8'), arrows: [['b7', 'b8']],
            text: 'A pawn that reaches the last rank must become a queen, a rook, a bishop or a knight. Almost always you choose a queen. In these lessons the pawn becomes a queen by itself.' },
          { type: 'stars', fen: fen('d2'), stars: ['d8', 'a5'], par: 6,
            text: 'Walk the pawn to the last rank, then use your new queen to collect the last star.' },
          { type: 'goal', fen: fen('Kg6 f7', 'Kh8'), goal: 'mate', solution: 'f8=Q#',
            text: 'Promote the pawn and give checkmate at the same time.' },
        ],
      },
      {
        id: 'draws',
        title: 'Draws',
        summary: 'When nobody wins.',
        icon: 'hourglass',
        steps: [
          { type: 'show', fen: fen('Kd4 Bc4', 'Ke6'),
            text: 'A game is drawn by stalemate; when neither side has enough pieces left to mate; when the same position appears three times; or after 50 moves by each side with no capture and no pawn move. Players may also agree to a draw.' },
          { type: 'quiz', fen: fen('Ke1 Bc4', 'Ke8'), verify: 'insufficient', text: 'King and bishop against a lone king. Can White still win?',
            choices: ['Yes', 'No, it is a draw'], answer: 1,
            after: 'A king and one bishop, or a king and one knight, can never force mate.' },
          { type: 'quiz', fen: fen('Ke1 Ra1', 'Ke8'), verify: 'sufficient', text: 'King and rook against a lone king?',
            choices: ['White can force mate', 'It is a draw'], answer: 0,
            after: 'A rook and king mate by force. You will practise it in the next unit.' },
          { type: 'quiz', text: 'The same position appears for the third time, with the same player to move. What happens?',
            choices: ['Either player can claim a draw', 'Nothing, play goes on'], answer: 0,
            after: 'Threefold repetition is a draw. It often saves a player who is losing.' },
        ],
      },
    ],
  },
  {
    id: 'endgame',
    title: 'Basic mates',
    text: 'Force checkmate against a lone king.',
    lessons: [
      {
        id: 'ladder',
        title: 'The ladder mate',
        summary: 'Two rooks take turns.',
        icon: 'r',
        steps: [
          { type: 'show', fen: fen('Kh1 Ra1 Rb2', 'Ke5'), arrows: [['a1', 'a5'], ['b2', 'b4']],
            text: 'Two rooks mate on their own, like climbing a ladder. One rook cuts the king off along a rank, the other gives check on the next rank, and they take turns until the king is on the edge.' },
          { type: 'play', fen: fen('Kh1 Ra1 Rb2', 'Ke5'), par: 8, limit: 25,
            text: 'Checkmate the black king. If it comes close to a rook, move that rook to the far side of the board.' },
        ],
      },
      {
        id: 'queen-mate',
        title: 'Queen and king',
        summary: 'Shrink the box, then mate.',
        icon: 'q',
        steps: [
          { type: 'show', fen: fen('Ke1 Qd1', 'Ke5'),
            text: 'With a queen, shrink the king\'s box: stay a knight\'s move away from it so it always keeps a square. Once it is stuck on the edge, bring your king up and mate. Always check that the king still has a move, or it is stalemate.' },
          { type: 'play', fen: fen('Ke1 Qd1', 'Ke5'), par: 12, limit: 30,
            text: 'Checkmate the black king with your queen and king.' },
        ],
      },
      {
        id: 'rook-mate',
        title: 'Rook and king',
        summary: 'The rook needs its king.',
        icon: 'k',
        steps: [
          { type: 'show', fen: fen('Ke1 Ra1', 'Ke5'),
            text: 'A single rook needs its king. Use the rook to cut the black king off, walk your king towards it, and push it to the edge. The mate comes with the rook checking along the edge while your king faces the black king.' },
          { type: 'play', fen: fen('Ke1 Ra1', 'Ke5'), par: 22, limit: 50,
            text: 'Checkmate the black king with your rook and king.' },
        ],
      },
    ],
  },
  {
    id: 'opening',
    title: 'Opening principles',
    text: 'How to start a game well.',
    lessons: [
      {
        id: 'centre',
        title: 'Take the centre',
        summary: 'The four squares that matter most.',
        icon: 'target',
        steps: [
          { type: 'show', fen: START, marks: ['d4', 'e4', 'd5', 'e5'],
            text: 'The four centre squares matter most. Pieces in the centre reach more squares, and pawns there take space and keep the enemy pieces away.' },
          { type: 'goal', fen: START, goal: ['accept', ['e4', 'd4']], solution: 'e4',
            text: 'Start the game with a pawn move that takes the centre.',
            after: 'A pawn on e4 or d4 holds a centre square and opens a path for a bishop and the queen.' },
          { type: 'quiz', fen: START, text: 'Which first move does the least for the centre?', choices: ['e4', 'd4', 'h4'], answer: 2,
            after: 'An edge pawn move does nothing for the centre and gets no piece closer to the game.' },
        ],
      },
      {
        id: 'develop',
        title: 'Develop your pieces',
        summary: 'Knights and bishops first.',
        icon: 'n',
        steps: [
          { type: 'show', fen: E4E5,
            text: 'Development means bringing the knights and bishops off the back rank. Bring out a new piece with each move, and don\'t hurry the queen out: enemy pieces can chase her and gain time.' },
          { type: 'goal', fen: E4E5, goal: ['accept', ['Nf3', 'Nc3', 'Bc4', 'Bb5']], solution: 'Nf3',
            text: 'Develop a knight or a bishop towards the centre.',
            after: 'Nf3 is the most common move here: it develops and attacks the pawn on e5.' },
          { type: 'goal', fen: E4E5NF3NC6, goal: ['accept', ['Bc4', 'Bb5', 'Nc3', 'd4']], solution: 'Bc4',
            text: 'Keep developing. Your bishop on f1 is still at home.',
            after: 'The bishop on c4 aims at f7, the weakest square in Black\'s camp, and clears the way for castling.' },
          { type: 'quiz', text: 'Why is bringing the queen out on move two usually a poor idea?',
            choices: ['The queen is worth less there', 'Black develops pieces while attacking her', 'It is against the rules'], answer: 1,
            after: 'Each time the queen has to run, Black brings out another piece for free.' },
        ],
      },
      {
        id: 'castle-early',
        title: 'Castle early',
        summary: 'King safe, rooks connected.',
        icon: 'shield',
        steps: [
          { type: 'goal', fen: ITALIAN, goal: ['castle', 'king'], solution: 'O-O',
            text: 'Your knight and bishop are out. Now castle to put your king in safety.',
            after: 'The king hides behind the pawns and the rook comes towards the centre.' },
          { type: 'quiz', text: 'Why castle early?',
            choices: ['The king is safer and a rook joins the game', 'It wins material', 'You must castle before move ten'], answer: 0,
            after: 'A king left in the centre gets caught when the centre opens up.' },
        ],
      },
    ],
  },
  {
    id: 'tactics',
    title: 'First tactics',
    text: 'The patterns behind the puzzles in the books.',
    lessons: [
      {
        id: 'fork',
        title: 'The fork',
        summary: 'Attack two pieces at once.',
        icon: 'n',
        theme: 'fork',
        steps: [
          { type: 'show', fen: fen('Kg1 Nc7', 'Ke8 Ra8', { turn: 'b' }), arrows: [['c7', 'e8'], ['c7', 'a8']],
            text: 'A fork is one piece attacking two at once. The opponent can save only one of them. Knights are the best forkers.' },
          { type: 'goal', fen: fen('Kg1 Nb5', 'Ke8 Ra8 f7 g7 h7'), goal: 'fork', solution: 'Nc7+',
            text: 'Fork the king and the rook with your knight.',
            after: 'The king must move, and the knight takes the rook.' },
          { type: 'goal', fen: fen('Kg1 Qd1 d2 f2 g2 h2', 'Kg8 Nc5 Be5 f7 g7 h7'), goal: 'fork', solution: 'd4',
            text: 'Fork two pieces with a pawn.',
            after: 'A pawn attacking two pieces is the cheapest fork of all. The queen protects the pawn, so taking it costs Black a piece.' },
          { type: 'goal', fen: fen('Kg1 Qd1 f2 g2 h2', 'Kg8 Ra8 g7 h7'), goal: 'fork', solution: 'Qd5+',
            text: 'Fork the king and the rook with your queen.',
            after: 'Qd8+ would also attack both, but the rook would simply take the queen.' },
        ],
      },
      {
        id: 'pin',
        title: 'The pin',
        summary: 'The piece in front can\'t move.',
        icon: 'b',
        theme: 'pin',
        steps: [
          { type: 'show', fen: fen('Kg1 Bb5', 'Ke8 Nc6', { turn: 'b' }), arrows: [['b5', 'e8']],
            text: 'A pin: a piece can\'t move away because something more valuable stands behind it on the same line. A piece pinned to the king may not move at all.' },
          { type: 'goal', fen: fen('Kg1 Bf1 f2 g2 h2', 'Ke8 Nc6 f7 g7 h7'), goal: 'pin', solution: 'Bb5',
            text: 'Pin the knight to the king.' },
          { type: 'goal', fen: fen('Kf1 Ra1 g2 h2', 'Ke8 Qe6 g7 h7'), goal: 'pin', solution: 'Re1',
            text: 'Pin the queen to the king with your rook.',
            after: 'The queen can\'t leave the e-file. The best Black can do is give her up for the rook.' },
        ],
      },
      {
        id: 'skewer',
        title: 'The skewer',
        summary: 'A pin the other way round.',
        icon: 'crosshair',
        theme: 'skewer',
        steps: [
          { type: 'show', fen: fen('Kh1 Rd1', 'Kd4 Rd8', { turn: 'b' }), arrows: [['d1', 'd8']],
            text: 'A skewer is a pin the other way round: the more valuable piece is in front. When it moves away, the piece behind it falls.' },
          { type: 'goal', fen: fen('Kh1 Ra1', 'Kd4 Rd8'), goal: 'skewer', solution: 'Rd1+',
            text: 'Skewer the king and the rook.',
            after: 'The king has to step aside, and the rook on d1 takes the rook on d8.' },
          { type: 'goal', fen: fen('Kg1 Bf1', 'Kf5 Qh7'), goal: 'skewer', solution: 'Bd3+',
            text: 'Skewer the king and the queen with your bishop.' },
        ],
      },
      {
        id: 'discovered',
        title: 'Discovered attack',
        summary: 'Move one piece, attack with another.',
        icon: 'eye',
        theme: 'discovered_attack',
        steps: [
          { type: 'show', fen: fen('Kg1 Re1 Ne4 f2 g2 h2', 'Kg8 Qe8 f7 g7 h7'), arrows: [['e1', 'e8']],
            text: 'A discovered attack: one piece moves out of the way and uncovers an attack by the piece behind it. The piece that moves can make a threat of its own at the same time.' },
          { type: 'goal', fen: fen('Kg1 Re1 Ne4 f2 g2 h2', 'Kg8 Qe8 f7 g7 h7'), goal: 'discovered', solution: 'Nf6+',
            text: 'Move the knight and uncover the rook\'s attack on the queen.',
            after: 'Any knight move uncovers the rook. The strongest is Nf6+: it gives check too, so Black has no time to save the queen.' },
          { type: 'line', fen: fen('Kg1 Re1 Ne4 f2 g2 h2', 'Kg8 Qe8 f7 g7 h7'), moves: ['Nf6+', 'gxf6', 'Rxe8+'],
            text: 'Now play it all the way: check with the knight, then take the queen.',
            after: 'Black took the knight to get out of check, and the rook won the queen.' },
        ],
      },
    ],
  },
];

export const LESSONS = UNITS.flatMap((unit, u) => unit.lessons.map((lesson) => ({ ...lesson, unit, unitNo: u + 1 })));
